# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.CharField(blank=True, default='', max_length=255, verbose_name='\u0424\u0440\u0430\u043a\u0446\u0438\u044f')),
                ('solidity', models.CharField(blank=True, default='', max_length=255, verbose_name='\u041f\u0440\u043e\u0447\u043d\u043e\u0441\u0442\u044c')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='\u041e\u0431\u044a\u0435\u043c')),
                ('start_date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('end_date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Location', verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Org', verbose_name='\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f-\u0437\u0430\u043a\u0430\u0437\u0447\u0438\u043a')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0442\u0440\u0435\u0431\u043d\u043e\u0441\u0442\u044c \u0432 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u0435',
                'verbose_name_plural': '\u041f\u043e\u0442\u0440\u0435\u0431\u043d\u043e\u0441\u0442\u0438 \u0432 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u0430\u0445',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b',
                'verbose_name_plural': '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='Pit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Location', verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Org', verbose_name='\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u044c\u0435\u0440',
                'verbose_name_plural': '\u041a\u0430\u0440\u044c\u0435\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='PitMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='\u041f\u043b\u043e\u0442\u043d\u043e\u0441\u0442\u044c')),
                ('fraction', models.CharField(blank=True, default='', max_length=255, verbose_name='\u0424\u0440\u0430\u043a\u0446\u0438\u044f')),
                ('solidity', models.CharField(blank=True, default='', max_length=255, verbose_name='\u041f\u0440\u043e\u0447\u043d\u043e\u0441\u0442\u044c')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043c\u0435\u0442\u0440 \u043a\u0443\u0431\u0438\u0447\u0435\u0441\u043a\u0438\u0439')),
                ('capacity', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='\u041e\u0431\u044a\u0435\u043c \u0432 \u0434\u0435\u043d\u044c, \u043c3')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pits.Material', verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b')),
                ('pit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pits.Pit', verbose_name='\u041a\u0430\u0440\u044c\u0435\u0440')),
            ],
            options={
                'verbose_name': '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b \u043a\u0430\u0440\u044c\u0435\u0440\u0430',
                'verbose_name_plural': '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044b \u043a\u0430\u0440\u044c\u0435\u0440\u043e\u0432',
            },
        ),
        migrations.AddField(
            model_name='demand',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pits.Material', verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b'),
        ),
        migrations.AlterUniqueTogether(
            name='pit',
            unique_together=set([('name', 'org')]),
        ),
    ]
