# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430/\u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
            preserve_default=False,
        ),
    ]
