# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pits', '0002_demand_dt_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandRemain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430/\u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('volume', models.PositiveIntegerField(verbose_name='\u041e\u0441\u0442\u0430\u0442\u043e\u043a \u0437\u0430 \u0434\u0430\u0442\u0443')),
            ],
        ),
        migrations.CreateModel(
            name='DemandResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430/\u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('volume', models.PositiveIntegerField(verbose_name='\u041e\u0431\u044a\u0435\u043c \u0437\u0430 \u0434\u0430\u0442\u0443')),
            ],
        ),
        migrations.AlterModelOptions(
            name='demand',
            options={'ordering': ('dt_created',), 'verbose_name': '\u041f\u043e\u0442\u0440\u0435\u0431\u043d\u043e\u0441\u0442\u044c \u0432 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u0435', 'verbose_name_plural': '\u041f\u043e\u0442\u0440\u0435\u0431\u043d\u043e\u0441\u0442\u0438 \u0432 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u0430\u0445'},
        ),
        migrations.AlterField(
            model_name='demand',
            name='volume',
            field=models.PositiveIntegerField(verbose_name='\u041e\u0431\u044a\u0435\u043c'),
        ),
        migrations.AlterField(
            model_name='pitmaterial',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='\u041e\u0431\u044a\u0435\u043c \u0432 \u0434\u0435\u043d\u044c, \u043c3'),
        ),
        migrations.AlterField(
            model_name='pitmaterial',
            name='density',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u041f\u043b\u043e\u0442\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='demandresult',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pits.Demand', verbose_name='\u041f\u043e\u0442\u0440\u0435\u0431\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='demandresult',
            name='pitmaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pits.PitMaterial', verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b \u043a\u0430\u0440\u044c\u0435\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='demandremain',
            name='pitmaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pits.PitMaterial', verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b \u043a\u0430\u0440\u044c\u0435\u0440\u0430'),
        ),
    ]
