# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pits', '0003_auto_20160919_1650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pitmaterial',
            unique_together=set([('pit', 'material', 'fraction', 'solidity')]),
        ),
    ]
