# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pits', '0004_auto_20160920_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemandResult',
            new_name='PitLoad',
        ),
        migrations.RenameModel(
            old_name='DemandRemain',
            new_name='PitRemain',
        ),
        migrations.AlterModelOptions(
            name='pitload',
            options={'verbose_name': '\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442 \u043f\u043e \u043f\u043e\u0442\u0440\u0435\u0431\u043d\u043e\u0441\u0442\u044f\u043c', 'verbose_name_plural': '\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u044b \u043f\u043e \u043f\u043e\u0442\u0440\u0435\u0431\u043d\u043e\u0441\u0442\u044f\u043c'},
        ),
        migrations.AlterModelOptions(
            name='pitremain',
            options={'verbose_name': '\u041e\u0441\u0442\u0430\u0442\u043a\u0438 \u043f\u043e \u043f\u043e\u0442\u0440\u0435\u0431\u043d\u043e\u0441\u0442\u044f\u043c', 'verbose_name_plural': '\u041e\u0441\u0442\u0430\u0442\u043a\u0438 \u043f\u043e \u043f\u043e\u0442\u0440\u0435\u0431\u043d\u043e\u0441\u0442\u044f\u043c'},
        ),
    ]
