# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pits', '0006_auto_20160930_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430/\u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('trips', models.PositiveIntegerField(verbose_name='\u0427\u0438\u0441\u043b\u043e \u0440\u0435\u0439\u0441\u043e\u0432 \u0430 \u0434\u0430\u0442\u0443')),
                ('volume', models.PositiveIntegerField(verbose_name='\u0421\u043a\u043e\u043b\u044c\u043a\u043e \u043f\u0435\u0440\u0435\u0432\u043e\u0437\u0438\u0442 \u0437\u0430 \u0434\u0435\u043d\u044c')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0433\u0440\u0443\u0437\u043e\u0432\u0438\u043a\u0430',
                'verbose_name_plural': '\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0433\u0440\u0443\u0437\u043e\u0432\u0438\u043a\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='TruckRemain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430/\u0432\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('trips', models.PositiveIntegerField(verbose_name='\u0427\u0438\u0441\u043b\u043e \u0440\u0435\u0439\u0441\u043e\u0432 \u043d\u0430 \u0434\u0430\u0442\u0443 \u043e\u0441\u0442\u0430\u043b\u043e\u0441\u044c')),
            ],
            options={
                'verbose_name': '\u041e\u0441\u0442\u0430\u0442\u043e\u043a \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0433\u0440\u0443\u0437\u043e\u0432\u0438\u043a\u0430',
                'verbose_name_plural': '\u041e\u0441\u0442\u0430\u0442\u043a\u0438 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0433\u0440\u0443\u0437\u043e\u0432\u0438\u043a\u043e\u0432',
            },
        ),
        migrations.AlterField(
            model_name='truck',
            name='trips',
            field=models.PositiveIntegerField(verbose_name='\u0427\u0438\u0441\u043b\u043e \u0440\u0435\u0439\u0441\u043e\u0432 \u0432 \u0434\u0435\u043d\u044c'),
        ),
        migrations.AlterUniqueTogether(
            name='pitload',
            unique_together=set([('date', 'demand', 'pitmaterial')]),
        ),
        migrations.AlterUniqueTogether(
            name='pitremain',
            unique_together=set([('date', 'pitmaterial')]),
        ),
        migrations.AddField(
            model_name='truckremain',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pits.Truck', verbose_name='\u0413\u0440\u0443\u0437\u043e\u0432\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='truckload',
            name='pitload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pits.PitLoad', verbose_name='\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u043a\u0430\u0440\u044c\u0435\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='truckload',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pits.Truck', verbose_name='\u0413\u0440\u0443\u0437\u043e\u0432\u0438\u043a'),
        ),
        migrations.AlterUniqueTogether(
            name='truckremain',
            unique_together=set([('truck', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='truckload',
            unique_together=set([('truck', 'date', 'pitload')]),
        ),
    ]
