# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('supplier', 'Юрлицо'), ('transporter', 'Перевозчик'), ('customer', 'Заказчик'), ('supervisor', 'Заказчик')], max_length=255, verbose_name='Тип')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название организации')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание, направление деятельности')),
                ('inn', models.CharField(blank=True, default='', max_length=255, verbose_name='ИНН')),
                ('director', models.CharField(blank=True, default='', max_length=255, verbose_name='Директор')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phones', models.TextField(blank=True, null=True, verbose_name='Телефоны')),
                ('fax', models.CharField(blank=True, default='', max_length=20, verbose_name='Факс')),
            ],
        ),
    ]
